# Generated by Django 3.1.4 on 2021-05-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='url',
            new_name='video',
        ),
    ]
